version: '3.7'

services:
  database-strong:
    image: postgres
    container_name: database-strong
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=strongdb
      - POSTGRES_DB=strong
    volumes:
      - pgdata:/data/postgres
    # network_mode: host

  # strong-back:
  #   build: .
  #   container_name: strong-back
  #   # ports:
  #   #   - 3333:3333
  #   volumes:
  #     - .:/usr/strong
  #   network_mode: host

volumes:
  pgdata:
    driver: local
